### ISSUE TITLE
[New Feature] Custom css export matching resolution

### ISSUE THREAD

**Issue by Fattimo** [shixuanhong/vite-plugin-css-export#2]
Hello!

Thank you so much for this plugin, it works great.

I was wondering if it would be possible to add a feature to put in custom boolean function to match a `export` css file, rather than strictly enforcing the `exportRE` regex.

https://github.com/shixuanhong/vite-plugin-css-export/blob/main/src/index.ts#L159 i.e., on the line here, replacing it with

```
if (isCSSRequest(id) && (customFunction ? customFunction(id) : exportRE?.test(id)))
```

I can put up a PR for this feature as well.

Thanks again!! :)

**Comment by shixuanhong** [comment]
This is a good idea, but the `customFunction` should not prevent the `exportER` from working properly.

**Comment by Fattimo** [comment]
thanks for implementing the feature! Do you know when it will be released?

**Comment by shixuanhong** [comment]
The new version has been released, thank you for your support.
